"""Inclde file_name to Screenshot

Revision ID: f6484b8c1bb9
Revises: bef3ef9fa20f
Create Date: 2023-11-07 16:54:36.012497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6484b8c1bb9'
down_revision: Union[str, None] = 'bef3ef9fa20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenshots', sa.Column('file_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenshots', 'file_name')
    # ### end Alembic commands ###
